#!/bin/sh

PREV_STATE=$(mpc status -f "%state%")

mpc toggle &>/dev/null

SONG=$(mpc current -f '%title%')
ARTIST=$(mpc current -f '%artist%')

SONG_FILE=$(mpdcsp)

if [ -z $SONG_FILE  ]; then
    exit
fi 

ffmpeg -y -i $SONG_FILE -an -c:v copy $HOME/.mpdcurrenttrackart.png &>/dev/null

# if the notification id is stored
if [ -f "$HOME/mpdnotificationid" ]; then
    # get the id of prev run
    PREVIOUS_SCRIPT_RUN_ID=$(cat $HOME/.mpdnotificationid)
   
    # create new notification to replace old one
    NOTIFICATION_ID=$(notify-send -r $PREVIOUS_SCRIPT_RUN_ID -i "$HOME/.mpdcurrenttrackart.png" " Now playing: $SONG - $ARTIST")

    rm $HOME/.mpdnotificationsid
else 
    NOTIFICATION_ID=$(notify-send -i "$HOME/.mpdcurrenttrackart.png" " Now playing: $SONG - $ARTIST")
    
    #write notification number to file
    echo $NOTIFICATION_ID >> $HOME/.mpdnotificationid
fi
#notify-send " Now playing: $SONG - $ARTIST"

rm $HOME/.mpdcurrenttrackart.png
